CREATE TABLE IF NOT EXISTS views (
    username   TEXT PRIMARY KEY NOT NULL,
    count      INTEGER NOT NULL DEFAULT 0,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_views_updated_at ON views(updated_at);
